/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author mrs_p
 */
public class Seleccion extends javax.swing.JFrame {

    /**
     * Creates new form Seleccion
     */
    public Seleccion() throws IOException {
        initComponents();
        
        /*BufferedImage image = null;
        image = ImageIO.read(new File("/imagenes/Inicio.png"));
        ImageIcon imageIcon = new ImageIcon(fitimage(image, lblTelcel.getWidth(), lblTelcel.getHeight()));
            lblTelcel.setIcon(imageIcon);*/
    }
    
    private Image fitimage(Image img , int w , int h)
    {
        BufferedImage resizedimage = new BufferedImage(w,h,BufferedImage.TYPE_INT_RGB);
        Graphics2D g2 = resizedimage.createGraphics();
        g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g2.drawImage(img, 0, 0,w,h,null);
        g2.dispose();
        return resizedimage;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        lblTelcel = new javax.swing.JLabel();
        lblMovistar = new javax.swing.JLabel();
        lblHoney = new javax.swing.JLabel();
        lblLG = new javax.swing.JLabel();
        lblSam = new javax.swing.JLabel();
        lblLetra = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 566));

        lblTelcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/tel.png"))); // NOI18N
        lblTelcel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTelcelMouseClicked(evt);
            }
        });

        lblMovistar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/movi.png"))); // NOI18N
        lblMovistar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMovistarMouseClicked(evt);
            }
        });

        lblHoney.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/honey.png"))); // NOI18N
        lblHoney.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHoneyMouseClicked(evt);
            }
        });

        lblLG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lgb.png"))); // NOI18N
        lblLG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLGMouseClicked(evt);
            }
        });

        lblSam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sams.png"))); // NOI18N
        lblSam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSamMouseClicked(evt);
            }
        });

        lblLetra.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        lblLetra.setForeground(new java.awt.Color(197, 132, 63));
        lblLetra.setText("Escoja una empresa");

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(lblSam))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHoney)
                            .addComponent(lblTelcel))
                        .addGap(61, 61, 61)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLG)
                            .addComponent(lblMovistar)))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(lblLetra)))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblLetra)
                .addGap(54, 54, 54)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTelcel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMovistar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHoney, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(lblLG)
                        .addGap(18, 18, 18)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSam)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblTelcelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTelcelMouseClicked
        Empersa1 empresa1=new Empersa1();
        empresa1.setLocationRelativeTo(null);
        empresa1.setSize(1040, 700);
        this.setVisible(false);
        empresa1.setVisible(true);
    }//GEN-LAST:event_lblTelcelMouseClicked

    private void lblMovistarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMovistarMouseClicked
         Empresa2 empresa2=new Empresa2();
         empresa2.setSize(1040, 700);
         empresa2.setLocationRelativeTo(null);
         this.setVisible(false);
         empresa2.setVisible(true);
    }//GEN-LAST:event_lblMovistarMouseClicked

    private void lblHoneyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHoneyMouseClicked
        // TODO add your handling code here:
        Empresa3 empresa3 = new Empresa3();
        empresa3.setSize(1040, 700);
        empresa3.setLocationRelativeTo(null);
        this.setVisible(false);
        empresa3.setVisible(true);
    }//GEN-LAST:event_lblHoneyMouseClicked

    private void lblLGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLGMouseClicked
        Empresa4 empresa4 = new Empresa4();
        empresa4.setSize(1040, 700);
        empresa4.setLocationRelativeTo(null);
        this.setVisible(false);
        empresa4.setVisible(true);
    }//GEN-LAST:event_lblLGMouseClicked

    private void lblSamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSamMouseClicked
        Empresa5 empresa5 = new Empresa5();
        empresa5.setSize(1040, 700);
        empresa5.setLocationRelativeTo(null);
        this.setVisible(false);
        empresa5.setVisible(true);
    }//GEN-LAST:event_lblSamMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblHoney;
    private javax.swing.JLabel lblLG;
    private javax.swing.JLabel lblLetra;
    private javax.swing.JLabel lblMovistar;
    private javax.swing.JLabel lblSam;
    private javax.swing.JLabel lblTelcel;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
